# Generated by Django 5.1.6 on 2025-08-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0047_persistentstore_review_blacklist_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='max_blogs',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='upgraded',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
