# Generated by Django 5.1.6 on 2025-08-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0048_alter_usersettings_max_blogs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='all_tools',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='post',
            name='all_tools',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='github_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
