# Generated by Django 5.1.6 on 2025-08-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0049_blog_all_tools_post_all_tools_post_comments_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
