# Generated by Django 5.1.6 on 2025-08-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0055_add_soft_delete_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dangerousreport',
            unique_together=set(),
        ),
    ]
