# Generated by Django 5.1.6 on 2025-08-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0056_remove_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='use_nickname',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dangerousreport',
            name='use_nickname',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='nickname',
            field=models.CharField(blank=True, help_text='Display name for comments and reports. Cannot be changed once set.', max_length=30, null=True, unique=True),
        ),
    ]
