# Generated by Django 5.1.6 on 2025-08-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0057_comment_use_nickname_dangerousreport_use_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='landing_styles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_path',
            field=models.CharField(default='space', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='nav',
            field=models.TextField(blank=True, default='[Home](/) [Feed](/feed/)'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='max_blogs',
            field=models.IntegerField(default=1),
        ),
    ]
