# Generated by Django 5.1.6 on 2025-08-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0058_usersettings_landing_styles_alter_blog_blog_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='discover_styles',
            field=models.TextField(blank=True),
        ),
    ]
