# Generated by Django 5.1.6 on 2025-08-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0059_usersettings_discover_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_template_draft',
            field=models.TextField(blank=True),
        ),
    ]
