# Generated by Django 5.1.6 on 2025-08-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0060_blog_post_template_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post_template_draft',
        ),
    ]
