# Generated by Django 5.1.6 on 2025-08-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0061_remove_blog_post_template_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_template_draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
